name: smart_travel
description: Travel app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.5.1"
  flutter: "^3.24.1"


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  flutter_staggered_grid_view: ^0.7.0

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  #    - images/apple_logo.png
  #    - images/google_logo.png
  #    - images/gosuslugi_logo.png
  #    - images/map.png
  #    - images/profile.png
  #    - images/main_logo.png
  #    - images/worship1.png
  #    - images/worship2.png
  #    - images/worship3.png
  #    - images/isaac.png
  #    - images/nimph.png
  #    - images/okhtenka.png
  #    - images/painter_willage.png
  #    - images/podlodka.png
  #    - images/shuvalovo.png
  #    - images/sfinks.png
  #    - images/sfinks1.jpg
  #    - icons/clear.png
  #    - icons/heart.png
  #    - icons/heart_filled.png
  #    - icons/search.png
  #    - icons/drawer.png
  #    - icons/export.png
  #    - icons/search.png
  #    - icons/settings.png
  #    - icons/back.png
  #    - icons/pensil.png
  #   - images/a_dot_ham.jpeg


  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

